apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Ganti dengan nilai Base64 dari password database Anda
  db-password: cGFzc3dvcmQ=
  # Ganti dengan nilai Base64 dari JWT secret Anda
  jwt-secret: 90385881f4876e643cdf5fa2b28c1494469133ddf0e6aee2784eeab3f4f342e82b51ea0c

# contoh : password : password

# echo -n 'password' | base64
# output : cGFzc3dvcmQ=