apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-verifikator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Sesuaikan ukuran sesuai kebutuhan
---
