apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bostang/secure-onboarding-system-frontend:latest
          env:
            - name: VITE_BACKEND_BASE_URL
              value: http://backend-service:8080 # Menggunakan nama service Kubernetes
            - name: VITE_VERIFICATOR_BASE_URL
              value: http://verifikator-service:8081 # Menggunakan nama service Kubernetes
          ports:
            - containerPort: 80
---
